name: Dispatch upload 2

on:
  workflow_dispatch:

jobs:
  test-naming:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ls -al    
    - name: Create some files to upload
      run: |
        mkdir -p my-artifact
        echo "This is a test file" > my-artifact/file1.txt
        dd if=/dev/urandom of=my-artifact/large-file.bin bs=1M count=10    
    - name: Upload artifact with fast compression (faster upload, larger size)
      uses: actions/upload-artifact@v4
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        name: fast-artifact
        path: my-artifact
        compression-level: 1  # Самый быстрый, но наименьшее сжатие    
    - name: Upload artifact with balanced compression
      uses: actions/upload-artifact@v4
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        name: balanced-artifact
        path: my-artifact
        compression-level: 6  # Баланс между скоростью и сжатием (значение по умолчанию)    
    - name: Upload artifact with maximum compression (slowest upload, smallest size)
      uses: actions/upload-artifact@v4
      env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        name: max-compression-artifact
        path: my-artifact
        compression-level: 9  # Максимальное сжатие, но медленнее 
