name: Dispatch Upload

on:
  workflow_dispatch:

jobs:
  display_inputs:
    runs-on: ubuntu-latest
    steps:

      - run: echo hi > world.txt
      - uses: actions/upload-artifact@v4
        with:
          # implicitly named as 'artifact'
          path: world.txt
      
      - run: echo howdy > extra-file.txt
      - uses: actions/upload-artifact@v4
        with:
          # also implicitly named as 'artifact', will fail here!
          path: extra-file.txt
