name: Dispatch

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Custom tag or label for this deployment"

      env:
        description: "Environment to run tests against"
        type: environment
        required: true

      str:
        description: "string to run tests against"
        type: string
        required: true

jobs:
  display_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display input values
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Timeout: ${{ inputs.timeout }} seconds"
          echo "Dry Run: ${{ inputs.dry_run }}"
          echo "Custom Tag: ${{ inputs.custom_tag }}"
          echo "Env: ${{ inputs.env }}"
          echo "Str: ${{ inputs.str }}"
