name: Other

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  display_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display input values
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Timeout: ${{ inputs.timeout }} seconds"
          echo "Dry Run: ${{ inputs.dry_run }}"
          echo "Custom Tag: ${{ inputs.custom_tag }}"
