name: Push

on:
  push:
    branches:
      - "*"

jobs:
  display_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display input values
        run: |
          echo "Environment: very important env!"
