name: Generate and Upload Large File

on:
  workflow_dispatch:

jobs:
  # generate-and-upload:
  #   runs-on: ubuntu-cloud-runner
  #   steps:
  #   - name: Generate file
  #     run: |
  #       # Создаем файл размером 400 МБ, заполненный нулями
  #       dd if=/dev/urandom of=file1.txt bs=10M count=6 status=none
  #       dd if=/dev/urandom of=file2.txt bs=10M count=6 status=none
  #       dd if=/dev/urandom of=file3.txt bs=10M count=6 status=none
  #       # Проверяем размер файла
  #       ls -lh file1.txt
        
  #   - name: Upload file as artifact
  #     uses: https://gitverse.ru/actions/upload-artifact@v4
  #     env:
  #         NODE_TLS_REJECT_UNAUTHORIZED: 0
  #     with:
  #       name: artifact-v4
  #       path: |
  #         file1.txt
  #       # Если время загрузки превышает таймаут, можно увеличить его (в минутах)
  #       retention-days: 1
  #       compression-level: 9 # maximum compression
    
  #   - name: Upload file as artifact 2
  #     uses: https://gitverse.ru/actions/upload-artifact@v4
  #     env:
  #         NODE_TLS_REJECT_UNAUTHORIZED: 0
  #     with:
  #       name: artifact-v4
  #       path: |
  #         file2.txt
  #         file3.txt
  #       # Если время загрузки превышает таймаут, можно увеличить его (в минутах)
  #       retention-days: 1
  #       compression-level: 1 # maximum compression

    #     # todo надо проверить когда несколько джобов проверить перезапись, ++ 
    #     # и несколько файлов в одной джобе +++
    #     # todo надо проверить несколько джобов дополняют один и тот же артефакт другими файлами ++ нет переписывают
  # upload-again:
  #   needs: generate-and-upload
  #   runs-on: ubuntu-cloud-runner
  #   steps:
  #     - name: Create a different file
  #       run: echo "goodbye world" > my-file.txt
  #     - name: Upload Artifact
  #       uses: https://gitverse.ru/actions/upload-artifact@v4
  #       with:
  #         name: artifact-v4 # NOTE: same artifact name
  #         path: my-file.txt
  #         overwrite: true
  test-naming:
    runs-on: ubuntu-latest
    steps:    
    - run: echo hi > world.txt
    - uses: https://gitverse.ru/actions/upload-artifact@v4
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        # implicitly named as 'artifact'
        path: world.txt    

    - run: echo howdy > extra-file.txt
    - uses: https://gitverse.ru/actions/upload-artifact@v4
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        # also implicitly named as 'artifact', will fail here!
        path: extra-file.txt


  # download:
  #   needs: upload-again
  #   runs-on: ubuntu-cloud-runner
  #   steps:
  #   - uses: https://gitverse.ru/actions/download-artifact@v4
  #     with:
  #       name: artifact-v4
  #   - run: ls -lah
