name: Generate and Upload Large File

on:
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Generate file
      run: |
        dd if=/dev/urandom of=file1.txt bs=10M count=6 status=none
        dd if=/dev/urandom of=file2.txt bs=10M count=6 status=none
        dd if=/dev/urandom of=file3.txt bs=10M count=6 status=none
    
    - name: Upload file as artifact 2
      uses: actions/upload-artifact@v4
      env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        name: artifact-v4
        path: |
          file2.txt
          file3.txt
        retention-days: 1
        compression-level: 1 # maximum compression

  upload-again:
    needs: generate-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Create a different file
        run: echo "goodbye world" > my-file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-v4 # NOTE: same artifact name
          path: my-file.txt
          # overwrite: true
  test-naming:
    runs-on: ubuntu-latest
    steps:    
    - run: echo hi > world.txt
    - uses: actions/upload-artifact@v4
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        # implicitly named as 'artifact'
        path: world.txt    

    - run: echo howdy > extra-file.txt
    - uses: actions/upload-artifact@v4
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        # also implicitly named as 'artifact', will fail here!
        path: extra-file.txt
        overwrite: true


  # download:
  #   needs: upload-again
  #   runs-on: ubuntu-cloud-runner
  #   steps:
  #   - uses: actions/download-artifact@v4
  #     with:
  #       name: artifact-v4
  #   - run: ls -lah
